### PR TITLE
Fixed - Can't Save Account Settings

### PR DESCRIPTION
**Pull request by ksaurabhsinha**
This is the fix for #14

### CODE REVIEW

**Comment by ksaurabhsinha** [comment]
Also added fix for other JS errors in Mozilla

**Comment by ksaurabhsinha** [comment]
Also added fix for other JS errors in Mozilla

**Comment by canvasowl** [comment]
Looks good, thanks for your contribution.

**Comment by ksaurabhsinha** [comment]
Pleasure!

**Pull request merged**
