### PR TITLE
Update to Laravel 5.1

### PR DESCRIPTION
**Pull request by ceesco53**
@canvasowl and anyone interested: This is an update PR to Laravel 5.1.  I'm actually using my PR at work now and plan on using it for the foreseeable future.  Use `.env.example` as a starting point for your environment variables and save to `.env`.  Testing was done on latest Vagrant/Homestead and on a Digital Ocean Droplet for production. 

So, in summary:

  1. Clone Laravel 5.1
  2. Add and update files from ribbbon.
  3. Test.

Moving forward, I plan on making a more agile/scrum oriented design in a new branch. Illl be glad to send another PR down the road or join up as a contributor.  This is really just a starting point for me. 

Thanks for posting this project, pretty cool stuff.

### CODE REVIEW

**Comment by canvasowl** [comment]
Thanks for this update and great job, however I will need to revert the pull request for the time being as I'm getting the error below:

Argument 1 passed to Illuminate\Foundation\Application::__construct() must be an instance of Illuminate\Http\Request, string given, called in vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 109

Please let me know if any more changes are needed from my side in order for this pull request to work properly (besides changing the .env file). Let me know if you have any questions.

**Comment by ceesco53** [comment]
@canvasowl I'm not seeing this error, but I could be missing something obvious, I haven't had my coffee.  Could you give me some more information on your setup/environment/versions? Steps to reproduce? I've got some free time today so I should be able to get this resolved soon.

**Comment by canvasowl** [comment]
Tricky as I'm at work right now and won't be home for another 9 hours. Maybe what we should do first is tell me what is needed in order to make this pull request work (could be that I messed up on my end). 

For example: After I pull your changes and change the environment configs, what else is needed to be done?

Let me know

**Comment by ceesco53** [comment]
Here is every step needed for me to complete setup of the dev branch in parity to the PR :

ssh into vagrant homestead
`cd Code`
`git clone -b dev git@github.com:ceesco53/ribbbon.git`
`cd ribbbon`
`cp .env.example .env`
(edit .env)
`composer install`
`php artisan key:generate`
`php artisan migrate`

quick tests I just did (although I did test all functions yesterday)

1) register
2) confirm I receive an email 
    - I left domain hardcoded in emails as ribbbon.com, I probably should update to env('APP_DOMAIN') in the email templates.
3) create first client "test"
4) edit client "test"
	- Add phone number, name, etc.
5) create "test" project
6) create "test" task for "test" project with weight 1

my environment:

Vagrant Homestead
Ubuntu 14.10
PHP 5.6.10-1+deb.sury.org~utopic+1

**Comment by canvasowl** [comment]
Looks about right. Will try again later tonight and let you know how it goes. Thanks again for your contribution and interest in this project.

**Comment by canvasowl** [comment]
@ceesco53 Follow your steps and it seems to be working me locally, going to run a few more tests. If good, will merge to master and push it to production in which case I would make you a contributor to project Ribbbon.

**Pull request merged**
